openapi: 3.0.3
info:
  title: Sistema de Gestión de Reservas
  description: API simple para gestionar reservas
  version: 1.0.0

servers:
  - url: http://localhost:3000/miapirest
    description: El servidor de la aplicación de gestión de reservas

components:
  schemas:
      Reserva:
        type: object
        required:
          - id_recurso
          - nombre_recurso
          - id_reserva_local
          - id_usuario
          - nombre_usuario
          - fecha
          - hora_inicio
          - hora_fin
          - coste
          - numero_plazas
          - motivo
          - disponible
        properties:
          id_recurso:
            type: integer
            example: 1
          id_reserva_local:
            type: integer
            example: 1
          id_usuario: 
            type: integer
            example: 1
          nombre_recurso:
            type: string
            example: "Recurso con un buen nombre"  
          nombre_usuario:
            type: string
            example: "Pepe Rodríguez Mas"  
          fecha:
            type: string
            format: date
            example: "2026-06-22"
          hora_inicio:
            type: string
            format: time
            example: "10:00:00"
          hora_fin:
            type: string
            format: time
            example: "17:00:00"
          coste:
            type: number
            format: decimal
            example: 20.00
          numero_plazas:
            type: integer
            example: 10
          motivo:
            type: string
            minLength: 1
            maxLength: 100
            example: "Haciendo una reserva para probar"
          observaciones:
            type: string
            minLength: 1
            maxLength: 100
            example: "No se ha de tener en cuenta esta reserva"
          disponible:
            type: boolean
            example: true  
      ReservaInput:
        type: object
        required:
          - id_recurso
          - fecha
          - hora_inicio
          - hora_fin
          - coste
          - numero_plazas
          - motivo
        properties:
          id_recurso:
            type: integer
            example: 1
          fecha:
            type: string
            format: date
            example: "2026-06-22"
          hora_inicio:
            type: string
            format: time
            example: "10:00:00"
          hora_fin:
            type: string
            format: time
            example: "17:00:00"
          coste:
            type: number
            format: decimal
            example: 20.00
          numero_plazas:
            type: integer
            example: 10
          motivo:
            type: string
            minLength: 1
            maxLength: 100
            example: "Haciendo una reserva para probar"
          observaciones:
            type: string
            minLength: 1
            maxLength: 100
            example: "No se ha de tener en cuenta esta reserva"
          disponible:
            type: boolean
            default: true
            example: true  
      Error:
        type: object
        properties:
          codigo:
            type: string
            example: "VALIDATION_ERROR"
          mensaje:
            type: string
            example: "Tienes varios errores"
          errores:
            type: array
            items:
              type: object
              required:
                - codigo
                - mensaje
              properties:
                codigo:
                  type: string
                  example: "NOT_FOUND"
                mensaje:
                  type: string
                  example: "No se ha encontrado la reserva"  
paths:
  /reservas:
    get:
      summary: Listar todas las reservas
      description: Devuelve un array con todas las reservas
      responses:
        '200':
          description: Lista de reservas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Reserva'                  
    post:
      summary: Crear una nueva reserva
      description: Añadir una nueva reserva
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReservaInput'
      responses:
        '201':
          description: La reserva ha sido creada correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reserva'
        '400':
          description: Datos inválidos
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"            
  /reservas/{reservaId}:
    patch:
      summary: Actualizar una reserva
      description: Actualiza el estado de una reserva (ANULADA-NO ANULADA)
      parameters:
        - name: reservaId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                disponible:
                  type: boolean
      responses:
        '200':
          description: Reserva actualizada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reserva'
        '404':
          description: La reserva no se ha encontrado  
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error" 
    delete:
      summary: Eliminar una reserva
      description: Elimina una reserva al completo
      parameters:
        - name: reservaId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: La reserva se ha eliminado correctamente
        '404':
          description: No se ha encontrado la reserva
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      